### ISSUE TITLE
servlet和Filter的生命周期

### ISSUE THREAD

**Issue by ladyBernard** [ladyBernard/java-web#10]
Filter是伴随着服务器的启动而开始，
            伴随着服务器的关闭而结束。

**Comment by B84TP3O17** [comment]
Servlet开始是第一个用户第一次请求，servlet只会被实例化一次。
init方法：第一个客户第一次请求才会被调用
service方法：每一次请求都会被调用
 只有在表单提交时，指定method为post时，提交方法才为post，包括超链接
